language: cpp
sudo: enabled
dist: bionic
services:
- mysql
before_install:
- mysql < stgaming_samp.sql
install:
- curl https://raw.githubusercontent.com/Southclaws/sampctl/master/install-deb.sh | sh
- sudo dpkg --add-architecture i386
- sudo apt update && sudo apt install -y g++-multilib
script:
- sampctl package ensure
- sampctl package build
- sampctl package run
